# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a8e8b349264b0c75f2ff3f4a1f6ad89202c00d1abf6a2e720f7cb217216aed31423e22398fd026bee33c13c9e488049f6230d615a3d22c60b35b3de49c741a1a

test:
  secret_key_base: bf90301d40c470f4baca3b55982000966fec8c7b4d89191870333b31541e725e9588aa285d56c0692b3f1ff08fead517f7fca527ff4935afec295477b9e55367

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
